export const TRANSACTION_DATA = [
    {
        Name:'Mohan',
        Date:'28/01/2024',
        Status:'Delivered',
        Amount:300
    },
    {
        Name:'King',
        Date:'28/01/2024',
        Status:'Delivered',
        Amount:300
    },
    {
        Name:'Ramu',
        Date:'28/01/2024',
        Status:'Delivered',
        Amount:300
    },
    {
        Name:'Mohan',
        Date:'28/01/2024',
        Status:'Delivered',
        Amount:300
    },
    {
        Name:'Mohan',
        Date:'28/01/2024',
        Status:'Delivered',
        Amount:300
    },
    {
        Name:'Mohan',
        Date:'28/01/2024',
        Status:'Delivered',
        Amount:300
    },
    {
        Name:'Mohan',
        Date:'28/01/2024',
        Status:'Delivered',
        Amount:300
    },
    {
        Name:'Mohan',
        Date:'28/01/2024',
        Status:'Delivered',
        Amount:300
    },
    {
        Name:'Mohan',
        Date:'28/01/2024',
        Status:'Delivered',
        Amount:300
    },
    {
        Name:'Mohan',
        Date:'28/01/2024',
        Status:'Delivered',
        Amount:300
    }
] 